/**
 * AI 词汇洞察 — Mock Data
 *
 * 覆盖需求中的 14 个 mock 场景。
 */

import type {
  HomeTeachingConcernCard,
  VocabularyInsightData,
  ErrorTypeItem,
  WeakWordItem,
  WeakStudentItem,
  GoodStudentItem,
  InterventionRecord,
} from './vocabularyInsightTypes'

// ═══════════════════════════════════════════════════════════
// 1. Home Teaching Concern Cards (4 cards)
// ═══════════════════════════════════════════════════════════

export const MOCK_VOCAB_CONCERN_CARDS: HomeTeachingConcernCard[] = [
  {
    id: 'vocab-concern-001',
    type: 'vocabulary_insight',
    status: '需关注',
    summary: 'Unit3 课标词错误较集中',
    targetPage: '/vocabulary-insight',
  },
  {
    id: 'vocab-concern-002',
    type: 'vocabulary_insight',
    status: '需关注',
    summary: '近期词汇拼写问题较集中',
    targetPage: '/vocabulary-insight',
  },
  {
    id: 'vocab-concern-003',
    type: 'vocabulary_insight',
    status: '建议关注',
    summary: '多名学生听音识词薄弱',
    targetPage: '/vocabulary-insight',
  },
  {
    id: 'vocab-concern-004',
    type: 'vocabulary_insight',
    status: '建议关注',
    summary: 'Unit2 语块掌握不稳定',
    targetPage: '/vocabulary-insight',
  },
]

// ═══════════════════════════════════════════════════════════
// 2. Error Types (7 categories)
// ═══════════════════════════════════════════════════════════

export const MOCK_ERROR_TYPES: ErrorTypeItem[] = [
  {
    type: 'spelling',
    label: '拼不对 / 默写错误',
    percent: 38,
    affectedStudentCount: 18,
    exampleWords: ['welcome', 'teacher', 'student'],
    aiReason: '默写练习频次不足，部分学生对单词音节和拼写规则掌握不牢，容易漏字母或错字母顺序。',
    recommendedActions: ['默写', '组卷', '词汇复习规划'],
    borderColor: '#f0a060',
    bgColor: '#fef8f0',
  },
  {
    type: 'listening_recognition',
    label: '听不准 / 听音识词弱',
    percent: 25,
    affectedStudentCount: 14,
    exampleWords: ['restaurant', 'delicious', 'vegetable'],
    aiReason: '学生听音训练不够，对单词发音与拼写的对应关系不熟悉，特别是多音节词。',
    recommendedActions: ['课后PK', '听写', '课后领读'],
    borderColor: '#e55',
    bgColor: '#fef0f0',
  },
  {
    type: 'phrase_chunk',
    label: '语块掌握弱',
    percent: 15,
    affectedStudentCount: 12,
    exampleWords: ['What would you like?', 'Help yourself.', 'Nice to meet you.'],
    aiReason: '语块整体理解和记忆较弱，学生往往能识别单个词但无法在语境中正确使用完整语块。',
    recommendedActions: ['课后领读', '组卷', '词汇复习规划'],
    borderColor: '#9ab3cc',
    bgColor: '#f5f7fa',
  },
  {
    type: 'contextual_usage',
    label: '不会用 / 语境应用弱',
    percent: 10,
    affectedStudentCount: 9,
    exampleWords: ['order', 'like', 'dinner'],
    aiReason: '学生在脱离课文语境后无法灵活运用词汇，缺少真实语境操练。',
    recommendedActions: ['组卷', '讲词'],
    borderColor: '#4b9fe8',
    bgColor: '#f0f6fc',
  },
  {
    type: 'en_to_cn',
    label: '认不出 / 英中匹配弱',
    percent: 6,
    affectedStudentCount: 7,
    exampleWords: ['menu', 'thirsty', 'hungry'],
    aiReason: '部分学生对英文拼写与中文释义的对应关系记忆模糊，尤其是低频词。',
    recommendedActions: ['课后PK', '默写'],
    borderColor: '#7b9cd6',
    bgColor: '#f0f4fc',
  },
  {
    type: 'cn_to_en_confusion',
    label: '词义混淆 / 中英匹配弱',
    percent: 4,
    affectedStudentCount: 5,
    exampleWords: ['chicken', 'fish', 'orange'],
    aiReason: '学生容易将拼写、词义或用法相近的词混淆，如 chicken（鸡肉/鸡）、fish（鱼/鱼肉）。',
    recommendedActions: ['讲词', '组卷'],
    borderColor: '#8e7cc3',
    bgColor: '#f6f0fc',
  },
  {
    type: 'pronunciation',
    label: '读不准 / 跟读发音弱',
    percent: 2,
    affectedStudentCount: 4,
    exampleWords: ['delicious', 'restaurant'],
    aiReason: '个别学生发音不够标准，特别是多音节词的重音和浊化音。',
    recommendedActions: ['课后领读', '课后PK'],
    borderColor: '#4caf50',
    bgColor: '#f0faf0',
  },
]

// ═══════════════════════════════════════════════════════════
// 3. Weak Words / Chunks (15 items — word + chunk)
// ═══════════════════════════════════════════════════════════

export const MOCK_WEAK_WORDS: WeakWordItem[] = [
  {
    id: 'ww-001',
    text: 'welcome',
    itemType: 'word',
    masteryRate: 42,
    errorRate: 58,
    affectedStudentCount: 18,
    mainErrorType: 'spelling',
    errorTypes: [
      { type: 'spelling', label: '拼不对', percent: 70 },
      { type: 'listening_recognition', label: '听不准', percent: 30 },
    ],
    typicalMistakes: [
      {
        studentId: 's-001',
        studentName: '张晓明',
        questionContext: '默写：Welcome to our school! → 根据中文提示写出英文单词',
        studentAnswer: 'welcom',
        correctAnswer: 'welcome',
        errorType: 'spelling',
        sourceTaskName: 'Unit 1 单词默写（1）',
        sourceTime: '2026-05-28',
      },
      {
        studentId: 's-002',
        studentName: '李华',
        questionContext: '听写：播放 /ˈwelkəm/ 的发音，请写出对应的英文单词',
        studentAnswer: 'wellcome',
        correctAnswer: 'welcome',
        errorType: 'spelling',
        sourceTaskName: 'Unit 1 听写练习',
        sourceTime: '2026-05-29',
      },
    ],
    sourceTasks: ['Unit 1 单词默写（1）', 'Unit 1 听写练习'],
    aiReason: 'welcome 音节 "wel-come" 分写导致学生误加字母，需强调单一 "l" 和 "c"。',
    recommendedActions: ['默写', '词汇复习规划'],
    priorityScore: 92,
  },
  {
    id: 'ww-002',
    text: 'student',
    itemType: 'word',
    masteryRate: 48,
    errorRate: 52,
    affectedStudentCount: 15,
    mainErrorType: 'spelling',
    errorTypes: [
      { type: 'spelling', label: '拼不对', percent: 60 },
      { type: 'en_to_cn', label: '认不出', percent: 40 },
    ],
    typicalMistakes: [
      {
        studentId: 's-003',
        studentName: '王芳',
        questionContext: '默写：She is a new student. → 拼写 student',
        studentAnswer: 'studant',
        correctAnswer: 'student',
        errorType: 'spelling',
        sourceTaskName: 'Unit 1 单词默写（1）',
        sourceTime: '2026-05-28',
      },
    ],
    sourceTasks: ['Unit 1 单词默写（1）'],
    aiReason: '第二音节 -dent 误写成 -dant，可能是受发音 /ə/ 的影响。',
    recommendedActions: ['默写', '组卷'],
    priorityScore: 88,
  },
  {
    id: 'ww-003',
    text: 'teacher',
    itemType: 'word',
    masteryRate: 52,
    errorRate: 48,
    affectedStudentCount: 13,
    mainErrorType: 'spelling',
    errorTypes: [
      { type: 'spelling', label: '拼不对', percent: 80 },
      { type: 'listening_recognition', label: '听不准', percent: 20 },
    ],
    typicalMistakes: [
      {
        studentId: 's-004',
        studentName: '刘洋',
        questionContext: '根据中文提示写出英文：老师 →',
        studentAnswer: 'techer',
        correctAnswer: 'teacher',
        errorType: 'spelling',
        sourceTaskName: 'Unit 1 词汇检测',
        sourceTime: '2026-05-30',
      },
    ],
    sourceTasks: ['Unit 1 词汇检测'],
    aiReason: '漏写 "a"，学生可能按直觉拼写 -er 结尾词。',
    recommendedActions: ['默写', '讲词'],
    priorityScore: 82,
  },
  {
    id: 'ww-004',
    text: 'restaurant',
    itemType: 'word',
    masteryRate: 35,
    errorRate: 65,
    affectedStudentCount: 20,
    mainErrorType: 'listening_recognition',
    errorTypes: [
      { type: 'listening_recognition', label: '听不准', percent: 55 },
      { type: 'spelling', label: '拼不对', percent: 45 },
    ],
    typicalMistakes: [
      {
        studentId: 's-005',
        studentName: '陈思雨',
        questionContext: '听音识词：播放 restaurant 录音，选出正确拼写',
        studentAnswer: 'restarant',
        correctAnswer: 'restaurant',
        errorType: 'listening_recognition',
        sourceTaskName: 'Unit 3 听音识词练习',
        sourceTime: '2026-05-31',
      },
    ],
    sourceTasks: ['Unit 3 听音识词练习'],
    aiReason: '多音节词，学生听音不够精准，且拼写复杂易出错。',
    recommendedActions: ['听写', '课后PK'],
    priorityScore: 95,
  },
  {
    id: 'ww-005',
    text: 'delicious',
    itemType: 'word',
    masteryRate: 38,
    errorRate: 62,
    affectedStudentCount: 19,
    mainErrorType: 'listening_recognition',
    errorTypes: [
      { type: 'listening_recognition', label: '听不准', percent: 50 },
      { type: 'pronunciation', label: '读不准', percent: 30 },
      { type: 'spelling', label: '拼不对', percent: 20 },
    ],
    typicalMistakes: [
      {
        studentId: 's-006',
        studentName: '赵子涵',
        questionContext: '听写：播放 delicious 的发音，写出单词',
        studentAnswer: 'delisous',
        correctAnswer: 'delicious',
        errorType: 'spelling',
        sourceTaskName: 'Unit 3 听写练习',
        sourceTime: '2026-05-31',
      },
    ],
    sourceTasks: ['Unit 3 听写练习', 'Unit 3 口语跟读'],
    aiReason: '发音和拼写都不够熟悉，-cious 词尾是拼写难点。',
    recommendedActions: ['听写', '课后领读', '词汇复习规划'],
    priorityScore: 91,
  },
  {
    id: 'ww-006',
    text: 'vegetable',
    itemType: 'word',
    masteryRate: 44,
    errorRate: 56,
    affectedStudentCount: 16,
    mainErrorType: 'listening_recognition',
    errorTypes: [
      { type: 'listening_recognition', label: '听不准', percent: 65 },
      { type: 'spelling', label: '拼不对', percent: 35 },
    ],
    typicalMistakes: [
      {
        studentId: 's-007',
        studentName: '周欣怡',
        questionContext: '听音识词：选出发音 /ˈvedʒtəbl/ 对应的单词',
        studentAnswer: 'vegtabel',
        correctAnswer: 'vegetable',
        errorType: 'spelling',
        sourceTaskName: 'Unit 3 听音识词练习',
        sourceTime: '2026-05-31',
      },
    ],
    sourceTasks: ['Unit 3 听音识词练习'],
    aiReason: 'vegetable 发音和拼写差距大，学生难以将 "vege" 与 /ˈvedʒ/ 对应。',
    recommendedActions: ['听写', '讲词'],
    priorityScore: 86,
  },
  {
    id: 'ww-007',
    text: 'hungry',
    itemType: 'word',
    masteryRate: 55,
    errorRate: 45,
    affectedStudentCount: 11,
    mainErrorType: 'en_to_cn',
    errorTypes: [
      { type: 'en_to_cn', label: '认不出', percent: 70 },
      { type: 'cn_to_en_confusion', label: '词义混淆', percent: 30 },
    ],
    typicalMistakes: [
      {
        studentId: 's-008',
        studentName: '吴俊杰',
        questionContext: '英译中：I am hungry. → 选出 "hungry" 的正确中文含义',
        studentAnswer: '口渴的',
        correctAnswer: '饥饿的',
        errorType: 'en_to_cn',
        sourceTaskName: 'Unit 3 词汇检测',
        sourceTime: '2026-05-30',
      },
    ],
    sourceTasks: ['Unit 3 词汇检测'],
    aiReason: 'hungry（饿）和 thirsty（渴）词义混淆，需要加强区分记忆。',
    recommendedActions: ['课后PK', '组卷'],
    priorityScore: 75,
  },
  {
    id: 'ww-008',
    text: 'thirsty',
    itemType: 'word',
    masteryRate: 50,
    errorRate: 50,
    affectedStudentCount: 12,
    mainErrorType: 'en_to_cn',
    errorTypes: [
      { type: 'en_to_cn', label: '认不出', percent: 55 },
      { type: 'spelling', label: '拼不对', percent: 45 },
    ],
    typicalMistakes: [
      {
        studentId: 's-009',
        studentName: '林小雨',
        questionContext: '英译中：Are you thirsty? → 选出 thirsty 的正确含义',
        studentAnswer: '饥饿的',
        correctAnswer: '口渴的',
        errorType: 'en_to_cn',
        sourceTaskName: 'Unit 3 词汇检测',
        sourceTime: '2026-05-30',
      },
    ],
    sourceTasks: ['Unit 3 词汇检测'],
    aiReason: '与 hungry 混淆，且拼写中 "th"、"irst" 部分也容易出错。',
    recommendedActions: ['讲词', '课后PK'],
    priorityScore: 78,
  },
  {
    id: 'ww-009',
    text: 'menu',
    itemType: 'word',
    masteryRate: 60,
    errorRate: 40,
    affectedStudentCount: 10,
    mainErrorType: 'en_to_cn',
    errorTypes: [
      { type: 'en_to_cn', label: '认不出', percent: 80 },
    ],
    typicalMistakes: [
      {
        studentId: 's-010',
        studentName: '黄子轩',
        questionContext: '英译中：Look at the menu. → 翻译 "menu"',
        studentAnswer: '男人',
        correctAnswer: '菜单',
        errorType: 'en_to_cn',
        sourceTaskName: 'Unit 3 阅读理解',
        sourceTime: '2026-05-29',
      },
    ],
    sourceTasks: ['Unit 3 阅读理解'],
    aiReason: 'menu 是短词但低频考，学生阅读中遇到时记忆模糊。',
    recommendedActions: ['讲词'],
    priorityScore: 65,
  },
  {
    id: 'ww-010',
    text: 'order',
    itemType: 'word',
    masteryRate: 56,
    errorRate: 44,
    affectedStudentCount: 9,
    mainErrorType: 'contextual_usage',
    errorTypes: [
      { type: 'contextual_usage', label: '不会用', percent: 60 },
      { type: 'en_to_cn', label: '认不出', percent: 40 },
    ],
    typicalMistakes: [
      {
        studentId: 's-011',
        studentName: '杨雪',
        questionContext: '语境填空：May I _____ your order? → 空格填哪个词？A. take B. get C. make',
        studentAnswer: 'get',
        correctAnswer: 'take',
        errorType: 'contextual_usage',
        sourceTaskName: 'Unit 3 语境填词',
        sourceTime: '2026-06-01',
      },
    ],
    sourceTasks: ['Unit 3 语境填词'],
    aiReason: 'order 作"点菜"讲时，固定搭配 "take one\'s order" 不熟。',
    recommendedActions: ['组卷', '讲词'],
    priorityScore: 72,
  },
  {
    id: 'ww-011',
    text: 'What would you like?',
    itemType: 'chunk',
    masteryRate: 40,
    errorRate: 60,
    affectedStudentCount: 17,
    mainErrorType: 'phrase_chunk',
    errorTypes: [
      { type: 'phrase_chunk', label: '语块掌握弱', percent: 80 },
      { type: 'contextual_usage', label: '不会用', percent: 20 },
    ],
    typicalMistakes: [
      {
        studentId: 's-012',
        studentName: '马天宇',
        questionContext: '补全对话：服务员问你想点什么，应该说：_____ → 填写完整句子',
        studentAnswer: 'What do you like?',
        correctAnswer: 'What would you like?',
        errorType: 'phrase_chunk',
        sourceTaskName: 'Unit 3 情景对话练习',
        sourceTime: '2026-05-31',
      },
    ],
    sourceTasks: ['Unit 3 情景对话练习'],
    aiReason: '学生习惯用 "do you" 替代 "would you"，对礼貌性请求的 would 用法不熟。',
    recommendedActions: ['课后领读', '组卷', '词汇复习规划'],
    priorityScore: 89,
  },
  {
    id: 'ww-012',
    text: 'Help yourself.',
    itemType: 'chunk',
    masteryRate: 36,
    errorRate: 64,
    affectedStudentCount: 16,
    mainErrorType: 'phrase_chunk',
    errorTypes: [
      { type: 'phrase_chunk', label: '语块掌握弱', percent: 75 },
      { type: 'contextual_usage', label: '不会用', percent: 25 },
    ],
    typicalMistakes: [
      {
        studentId: 's-013',
        studentName: '孙佳琪',
        questionContext: '翻译：请自便 → 填写英文表达',
        studentAnswer: 'Help youself',
        correctAnswer: 'Help yourself.',
        errorType: 'phrase_chunk',
        sourceTaskName: 'Unit 3 句子翻译练习',
        sourceTime: '2026-06-01',
      },
    ],
    sourceTasks: ['Unit 3 句子翻译练习'],
    aiReason: '反身代词 yourself 拼写错误，"Help yourself" 整体语块记忆不牢。',
    recommendedActions: ['课后领读', '词汇复习规划'],
    priorityScore: 87,
  },
  {
    id: 'ww-013',
    text: 'Nice to meet you.',
    itemType: 'chunk',
    masteryRate: 62,
    errorRate: 38,
    affectedStudentCount: 10,
    mainErrorType: 'phrase_chunk',
    errorTypes: [
      { type: 'phrase_chunk', label: '语块掌握弱', percent: 70 },
    ],
    typicalMistakes: [
      {
        studentId: 's-001',
        studentName: '张晓明',
        questionContext: '补全对话：初次见面说 → _____',
        studentAnswer: 'Nice to meet you too',
        correctAnswer: 'Nice to meet you.',
        errorType: 'phrase_chunk',
        sourceTaskName: 'Unit 1 情景对话',
        sourceTime: '2026-05-25',
      },
    ],
    sourceTasks: ['Unit 1 情景对话'],
    aiReason: '学生习惯回复时加 too，但在首次问候场景中无需 too。',
    recommendedActions: ['课后领读'],
    priorityScore: 62,
  },
  // Items to be FILTERED OUT by vocabularyDataFilter:
  {
    id: 'ww-014',
    text: 'I',
    itemType: 'word',
    masteryRate: 95,
    errorRate: 5,
    affectedStudentCount: 1,
    mainErrorType: 'pronunciation',
    errorTypes: [{ type: 'pronunciation', label: '读不准', percent: 100 }],
    typicalMistakes: [],
    sourceTasks: [],
    aiReason: '代词 I 的高掌握率不代表词汇能力，属于低价值统计项。',
    recommendedActions: [],
    priorityScore: 5,
  },
  {
    id: 'ww-015',
    text: 'the',
    itemType: 'word',
    masteryRate: 98,
    errorRate: 2,
    affectedStudentCount: 0,
    mainErrorType: 'pronunciation',
    errorTypes: [{ type: 'pronunciation', label: '读不准', percent: 100 }],
    typicalMistakes: [],
    sourceTasks: [],
    aiReason: '冠词 the 不应作为错词对待，属于低价值统计项。',
    recommendedActions: [],
    priorityScore: 2,
  },
]

// ═══════════════════════════════════════════════════════════
// 4. Weak Students (8+ people)
// ═══════════════════════════════════════════════════════════

export const MOCK_WEAK_STUDENTS: WeakStudentItem[] = [
  {
    id: 's-001',
    name: '张晓明',
    masteryRate: 48,
    weakWords: ['welcome', 'restaurant', 'delicious', 'Vegetable'],
    mainErrorTypes: ['拼不对', '听不准'],
    typicalContext: '默写 Unit 1 & Unit 3 时多次将 welcome 写成 welcom，restaurant 写成 restarant',
    recentTrend: 'stable',
    recommendedActions: ['默写', '听写'],
    weaknessPriorityScore: 92,
    errorTypeDistribution: [
      { type: 'spelling', label: '拼不对', percent: 50 },
      { type: 'listening_recognition', label: '听不准', percent: 30 },
      { type: 'phrase_chunk', label: '语块掌握弱', percent: 20 },
    ],
    weakWordDetails: [],
  },
  {
    id: 's-002',
    name: '李华',
    masteryRate: 52,
    weakWords: ['welcome', 'student', 'teacher'],
    mainErrorTypes: ['拼不对'],
    typicalContext: '默写时 wellcome/techer/studant 反复出现',
    recentTrend: 'declining',
    recommendedActions: ['默写', '组卷'],
    weaknessPriorityScore: 85,
    errorTypeDistribution: [
      { type: 'spelling', label: '拼不对', percent: 60 },
      { type: 'en_to_cn', label: '认不出', percent: 25 },
      { type: 'listening_recognition', label: '听不准', percent: 15 },
    ],
    weakWordDetails: [],
  },
  {
    id: 's-003',
    name: '王芳',
    masteryRate: 50,
    weakWords: ['student', 'hungry', 'thirsty'],
    mainErrorTypes: ['拼不对', '认不出'],
    typicalContext: 'student→studant，hungry/thirsty 词义反复混淆',
    recentTrend: 'stable',
    recommendedActions: ['默写', '讲词'],
    weaknessPriorityScore: 80,
    errorTypeDistribution: [
      { type: 'spelling', label: '拼不对', percent: 40 },
      { type: 'en_to_cn', label: '认不出', percent: 35 },
      { type: 'cn_to_en_confusion', label: '词义混淆', percent: 25 },
    ],
    weakWordDetails: [],
  },
  {
    id: 's-004',
    name: '刘洋',
    masteryRate: 55,
    weakWords: ['teacher', 'delicious', 'menu'],
    mainErrorTypes: ['拼不对', '听不准'],
    typicalContext: 'techer/delisous/menu 听力和拼写均弱',
    recentTrend: 'improving',
    recommendedActions: ['听写', '课后PK'],
    weaknessPriorityScore: 75,
    errorTypeDistribution: [
      { type: 'spelling', label: '拼不对', percent: 45 },
      { type: 'listening_recognition', label: '听不准', percent: 35 },
      { type: 'en_to_cn', label: '认不出', percent: 20 },
    ],
    weakWordDetails: [],
  },
  {
    id: 's-005',
    name: '陈思雨',
    masteryRate: 42,
    weakWords: ['restaurant', 'vegetable', 'delicious'],
    mainErrorTypes: ['听不准', '拼不对'],
    typicalContext: '多音节词听写几乎全错，restarant/vegtabel/delisous',
    recentTrend: 'declining',
    recommendedActions: ['听写', '课后领读', '词汇复习规划'],
    weaknessPriorityScore: 90,
    errorTypeDistribution: [
      { type: 'listening_recognition', label: '听不准', percent: 55 },
      { type: 'spelling', label: '拼不对', percent: 30 },
      { type: 'pronunciation', label: '读不准', percent: 15 },
    ],
    weakWordDetails: [],
  },
  {
    id: 's-006',
    name: '赵子涵',
    masteryRate: 58,
    weakWords: ['What would you like?', 'Help yourself.'],
    mainErrorTypes: ['语块掌握弱'],
    typicalContext: 'What do you like? / Help youself 语块整体错误',
    recentTrend: 'stable',
    recommendedActions: ['课后领读', '词汇复习规划'],
    weaknessPriorityScore: 78,
    errorTypeDistribution: [
      { type: 'phrase_chunk', label: '语块掌握弱', percent: 50 },
      { type: 'contextual_usage', label: '不会用', percent: 30 },
      { type: 'spelling', label: '拼不对', percent: 20 },
    ],
    weakWordDetails: [],
  },
  {
    id: 's-007',
    name: '周欣怡',
    masteryRate: 46,
    weakWords: ['vegetable', 'order', 'thirsty'],
    mainErrorTypes: ['听不准', '不会用'],
    typicalContext: 'vegetable 听写拼错，order 的语境搭配不会用',
    recentTrend: 'declining',
    recommendedActions: ['听写', '组卷'],
    weaknessPriorityScore: 82,
    errorTypeDistribution: [
      { type: 'listening_recognition', label: '听不准', percent: 40 },
      { type: 'contextual_usage', label: '不会用', percent: 30 },
      { type: 'spelling', label: '拼不对', percent: 30 },
    ],
    weakWordDetails: [],
  },
  {
    id: 's-008',
    name: '吴俊杰',
    masteryRate: 52,
    weakWords: ['hungry', 'menu', 'Nice to meet you.'],
    mainErrorTypes: ['认不出', '语块掌握弱'],
    typicalContext: 'hungry/thirsty 词义混，菜单翻译成"男人"',
    recentTrend: 'stable',
    recommendedActions: ['讲词', '课后PK'],
    weaknessPriorityScore: 70,
    errorTypeDistribution: [
      { type: 'en_to_cn', label: '认不出', percent: 45 },
      { type: 'phrase_chunk', label: '语块掌握弱', percent: 30 },
      { type: 'cn_to_en_confusion', label: '词义混淆', percent: 25 },
    ],
    weakWordDetails: [],
  },
]

// ═══════════════════════════════════════════════════════════
// 5. Good Students (6+ people)
// ═══════════════════════════════════════════════════════════

export const MOCK_GOOD_STUDENTS: GoodStudentItem[] = [
  { id: 'g-001', name: '林小雨', masteryRate: 92, masteredCount: 48, highlight: '课标词全掌握，语块运用灵活', stability: 'stable' },
  { id: 'g-002', name: '杨雪', masteryRate: 88, masteredCount: 44, highlight: '听音识词准确率高，拼写稳定', stability: 'improving' },
  { id: 'g-003', name: '黄子轩', masteryRate: 90, masteredCount: 46, highlight: '近两周进步明显，语块掌握扎实', stability: 'improving' },
  { id: 'g-004', name: '孙佳琪', masteryRate: 85, masteredCount: 42, highlight: '默写几乎零失误，语境运用良好', stability: 'stable' },
  { id: 'g-005', name: '马天宇', masteryRate: 87, masteredCount: 43, highlight: '多音节词掌握好，跟读发音标准', stability: 'stable' },
  { id: 'g-006', name: '陈思琪', masteryRate: 84, masteredCount: 40, highlight: '语块记忆牢固，情景对话表现出色', stability: 'improving' },
]

// ═══════════════════════════════════════════════════════════
// 6. Full VocabularyInsightData
// ═══════════════════════════════════════════════════════════

export const MOCK_VOCABULARY_INSIGHT: VocabularyInsightData = {
  classId: 'class-7-3',
  className: '初一 1 班',
  unitId: 'unit-3',
  unitName: 'Unit 3 — Food and Drinks',
  timeRange: '7d',
  updatedAt: '今天 10:30',
  summary: 'Unit3 课标词错误较集中，主要问题是拼写错误和听音识词弱。welcome、student、teacher 出错人数较多，建议先生成词汇复习规划，再配合默写和课后领读进行巩固。',
  metrics: {
    masteryRate: 68,
    practicedWordCount: 85,
    weakWordCount: 13,
    weakStudentCount: 8,
    mainWeakType: '拼不对 / 默写错误',
  },
  errorTypes: MOCK_ERROR_TYPES,
  weakWords: MOCK_WEAK_WORDS,
  weakStudents: MOCK_WEAK_STUDENTS,
  goodStudents: MOCK_GOOD_STUDENTS,
  interventionRecords: [],
}

// ═══════════════════════════════════════════════════════════
// 7. Intervention Records
// ═══════════════════════════════════════════════════════════

export const MOCK_INTERVENTION_RECORDS: InterventionRecord[] = [
  {
    id: 'ir-001',
    time: '2026-05-28 14:30',
    type: '词汇复习方案',
    name: 'Unit 3 高频错词巩固计划',
    target: '初一 1 班（全班）',
    taskCount: 3,
    status: '已完成',
    completionSummary: '3/3 任务全部完成，18 人参与',
    effectSummary: {
      beforeMasteryRate: 52,
      afterMasteryRate: 68,
      stillWeakWords: ['welcome', 'student'],
      improvedStudents: 14,
      needMorePracticeStudents: 4,
      suggestion: '重点错词掌握率 52% → 68%。welcome、student 仍有部分学生掌握不稳定，建议继续安排一次错词默写。',
    },
  },
  {
    id: 'ir-002',
    time: '2026-05-25 10:00',
    type: '默写',
    name: 'Unit 3 课标词默写',
    target: '初一 1 班（全班）',
    taskCount: 1,
    status: '已完成',
    completionSummary: '1/1 任务完成，全体参与',
    effectSummary: {
      beforeMasteryRate: 45,
      afterMasteryRate: 58,
      stillWeakWords: ['delicious', 'restaurant'],
      improvedStudents: 16,
      needMorePracticeStudents: 2,
      suggestion: '默写后整体提升明显，但 delicious、restaurant 等长短词仍需强化听写。',
    },
  },
  {
    id: 'ir-003',
    time: '2026-05-22 09:00',
    type: '课后领读',
    name: 'Unit 3 语块领读练习',
    target: '薄弱学生（8 人）',
    taskCount: 2,
    status: '部分完成',
    completionSummary: '1/2 任务完成，6 人参与领读',
    effectSummary: {
      beforeMasteryRate: 40,
      afterMasteryRate: 48,
      stillWeakWords: ['Help yourself.', 'What would you like?'],
      improvedStudents: 4,
      needMorePracticeStudents: 4,
      suggestion: '语块整体提升幅度有限，建议结合情景对话练习加强语境应用。',
    },
  },
]

// ═══════════════════════════════════════════════════════════
// 8. Review Plan Templates (4 goal types)
// ═══════════════════════════════════════════════════════════

import type { ReviewPlanConfig, ReviewPlanTask, ReviewGoal } from './vocabularyInsightTypes'

export function getReviewPlanConfig(goal: ReviewGoal): ReviewPlanConfig {
  const meta: Record<ReviewGoal, ReviewPlanConfig> = {
    quick_fix: {
      goal: 'quick_fix',
      dayCount: 3,
      wordsPerDay: 30,
      reviewScope: '高频错词、薄弱语块',
      targetStudents: '全班',
      strategy: '集中突破近期错词，默写 + 中英检测 + 错词复练三轮巩固',
      aiReason: '近 7 天错词数据集中，适合短期快速巩固。默写检测拼写，中英检测强化释义匹配，错词复练确保掌握。',
    },
    current_unit: {
      goal: 'current_unit',
      dayCount: 7,
      wordsPerDay: 50,
      reviewScope: '当前单元课标词、高频错词、语块',
      targetStudents: '全班',
      strategy: '课标词系统复习 + 错词语块巩固 + 语境填词/词形变化',
      aiReason: 'Unit 3 课标词 25 个，错词 13 个，语块 10 个。先复习课标词打基础，再针对错词语块重点巩固，最后用语境填词检验应用能力。',
    },
    stage_exam: {
      goal: 'stage_exam',
      dayCount: 14,
      wordsPerDay: 80,
      reviewScope: '课标词、新课标词、真题高频词、核心错词',
      targetStudents: '全班',
      strategy: '课标词/新课标词分批复习 + 真题例句复现 + 高频错词组卷 + 每周滚动检测',
      aiReason: '阶段复习需要覆盖课标词和真题高频词共约 200 个，分 4 批复习较为合理。每周安排一次滚动检测确保前面的内容不遗忘。',
    },
    weak_student: {
      goal: 'weak_student',
      dayCount: 7,
      wordsPerDay: 30,
      reviewScope: '个人薄弱词、核心错词语块',
      targetStudents: '薄弱学生（8 人）',
      strategy: '个人薄弱词默写 + 错词复练 + 听音识词/语块专项 + 小组补练',
      aiReason: '8 名薄弱学生各有不同的弱项，需根据个人错误类型分配合适的练习。张晓明、陈思雨重点练听写，赵子涵重点练语块。',
    },
    custom: {
      goal: 'custom',
      dayCount: 7,
      wordsPerDay: 50,
      reviewScope: '自选词汇范围',
      targetStudents: '全班',
      strategy: '根据老师自定义的词汇范围和复习频次灵活配置，支持错词滚动复现。',
      aiReason: '自定义规划可以灵活搭配词汇来源和复习节奏，适合有特定教学目标的场景。',
    },
  }
  return meta[goal]
}

export function getReviewPlanTasks(goal: ReviewGoal): ReviewPlanTask[] {
  const taskMap: Record<ReviewGoal, ReviewPlanTask[]> = {
    quick_fix: [
      { id: 'qt-1', checked: true, name: '高频错词默写', contentScope: 'Unit 3 高频错词 13 个', taskType: '默写', targetType: 'class', targetName: '初一 1 班', scheduledTime: '今天 15:00', deadline: '明天 08:00', editable: true },
      { id: 'qt-2', checked: true, name: '中英检测', contentScope: '高频错词 + 课标词 25 个', taskType: '中英检测', targetType: 'class', targetName: '初一 1 班', scheduledTime: '明天 09:00', deadline: '明天 20:00', editable: true },
      { id: 'qt-3', checked: true, name: '错词复练', contentScope: '前两轮仍错的词', taskType: '错词复练', targetType: 'class', targetName: '初一 1 班', scheduledTime: '后天 09:00', deadline: '后天 20:00', editable: true },
    ],
    current_unit: [
      { id: 'cu-1', checked: true, name: 'Unit 3 课标词复习', contentScope: 'Unit 3 课标词 25 个', taskType: '词表识记', targetType: 'class', targetName: '初一 1 班', scheduledTime: '第 1 天 09:00', deadline: '第 2 天 08:00', editable: true },
      { id: 'cu-2', checked: true, name: '高频错词 + 语块巩固', contentScope: '错词 13 个 + 语块 10 个', taskType: '默写', targetType: 'class', targetName: '初一 1 班', scheduledTime: '第 3 天 09:00', deadline: '第 4 天 08:00', editable: true },
      { id: 'cu-3', checked: true, name: '语境填词 / 词形变化', contentScope: '课标词应用练习', taskType: '语境填词', targetType: 'class', targetName: '初一 1 班', scheduledTime: '第 5 天 09:00', deadline: '第 6 天 08:00', editable: true },
      { id: 'cu-4', checked: true, name: '单元词汇综合检测', contentScope: '全部课标词 + 错词语块', taskType: '组卷检测', targetType: 'class', targetName: '初一 1 班', scheduledTime: '第 7 天 09:00', deadline: '第 7 天 20:00', editable: true },
    ],
    stage_exam: [
      { id: 'se-1', checked: true, name: '课标词第一批复习', contentScope: 'Unit 1-2 课标词 50 个', taskType: '词表识记', targetType: 'class', targetName: '初一 1 班', scheduledTime: '第 1 天 09:00', deadline: '第 3 天 08:00', editable: true },
      { id: 'se-2', checked: true, name: '课标词第二批复习', contentScope: 'Unit 3-4 课标词 50 个', taskType: '词表识记', targetType: 'class', targetName: '初一 1 班', scheduledTime: '第 4 天 09:00', deadline: '第 6 天 08:00', editable: true },
      { id: 'se-3', checked: true, name: '真题例句复现', contentScope: '中考真题高频词 30 个', taskType: '真题例句复现', targetType: 'class', targetName: '初一 1 班', scheduledTime: '第 7 天 09:00', deadline: '第 8 天 20:00', editable: true },
      { id: 'se-4', checked: true, name: '高频错词组卷', contentScope: '全部单元错词 30 个', taskType: '高频错词组卷', targetType: 'class', targetName: '初一 1 班', scheduledTime: '第 9 天 09:00', deadline: '第 10 天 20:00', editable: true },
      { id: 'se-5', checked: true, name: '每周滚动检测（Week 1）', contentScope: '第 1-7 天复习内容', taskType: '组卷检测', targetType: 'class', targetName: '初一 1 班', scheduledTime: '第 8 天 09:00', deadline: '第 8 天 20:00', editable: true },
      { id: 'se-6', checked: true, name: '每周滚动检测（Week 2）', contentScope: '第 1-14 天全部内容', taskType: '组卷检测', targetType: 'class', targetName: '初一 1 班', scheduledTime: '第 14 天 09:00', deadline: '第 14 天 20:00', editable: true },
    ],
    weak_student: [
      { id: 'ws-1', checked: true, name: '个人薄弱词默写', contentScope: '每人 8-12 个薄弱词', taskType: '默写', targetType: 'student', targetName: '张晓明、陈思雨等 8 人', scheduledTime: '第 1 天 15:00', deadline: '第 2 天 08:00', editable: true },
      { id: 'ws-2', checked: true, name: '个人错词复练', contentScope: '默写中仍错的词', taskType: '错词复练', targetType: 'student', targetName: '张晓明、陈思雨等 8 人', scheduledTime: '第 3 天 15:00', deadline: '第 4 天 08:00', editable: true },
      { id: 'ws-3', checked: true, name: '听音识词 / 语块专项', contentScope: '听不准词 6 个 + 语块 4 个', taskType: '听音识词', targetType: 'student', targetName: '张晓明、陈思雨、赵子涵', scheduledTime: '第 5 天 15:00', deadline: '第 6 天 08:00', editable: true },
      { id: 'ws-4', checked: true, name: '小组补练任务', contentScope: '每人最后薄弱词', taskType: '词表识记', targetType: 'group', targetName: '4 人/组 × 2 组', scheduledTime: '第 7 天 09:00', deadline: '第 7 天 20:00', editable: true },
    ],
    custom: [
      { id: 'cu-1', checked: true, name: '自选词汇第一轮', contentScope: '自选词汇范围 50 个', taskType: '词表识记', targetType: 'class', targetName: '初一 1 班', scheduledTime: '第 1 天 09:00', deadline: '第 2 天 08:00', editable: true },
      { id: 'cu-2', checked: true, name: '自选词汇第二轮', contentScope: '自选词汇范围 + 前轮错词', taskType: '默写', targetType: 'class', targetName: '初一 1 班', scheduledTime: '第 3 天 09:00', deadline: '第 4 天 08:00', editable: true },
      { id: 'cu-3', checked: true, name: '语境应用练习', contentScope: '自选词汇应用', taskType: '语境填词', targetType: 'class', targetName: '初一 1 班', scheduledTime: '第 5 天 09:00', deadline: '第 6 天 08:00', editable: true },
      { id: 'cu-4', checked: true, name: '综合检测', contentScope: '全部词汇 + 滚动错词', taskType: '组卷检测', targetType: 'class', targetName: '初一 1 班', scheduledTime: '第 7 天 09:00', deadline: '第 7 天 20:00', editable: true },
    ],
  }
  return taskMap[goal]
}
