/**
 * 词汇复习计划作业集合 — Mock 数据
 */
import type { ReviewPlanAssignmentCollection } from './reviewPlanAssignmentTypes'

export const MOCK_REVIEW_PLAN_ASSIGNMENTS: ReviewPlanAssignmentCollection[] = [
  {
    id: 'plan-001',
    title: '近期待巩固词复习计划',
    planType: 'quick_fix',
    className: '2023级A18班',
    wordCount: 8,
    dayCount: 5,
    reviewDays: [1, 3, 5],
    taskCount: 3,
    wordsPerDay: 30,
    status: 'in_progress',
    progressSummary: '已完成 1/3 份任务',
    currentTaskLabel: 'Day 3 巩固回滚任务',
    pendingRetryLabel: '待补做：3 人',
    publishedAt: '2026-06-12T09:00:00Z',
    goalLabel: '快速巩固近期错词',
    days: [
      {
        dayIndex: 1,
        dayLabel: 'Day 1 复习任务',
        taskType: 'main',
        questionSummary: '30 道主复习题',
        mainQuestionCount: 30,
        rollbackQuestionCount: 0,
        status: 'completed',
        submittedCount: 38,
        totalStudents: 41,
        reportUrl: '/practice-reports?plan=plan-001&day=1',
        startTime: '6月12日 09:00',
        deadline: '6月12日 23:59',
        id: 'plan-001-day-1',
      },
      {
        dayIndex: 3,
        dayLabel: 'Day 3 巩固回滚任务',
        taskType: 'consolidation',
        questionSummary: '24 道主复习题 + 6 道动态回滚题',
        mainQuestionCount: 24,
        rollbackQuestionCount: 6,
        status: 'in_progress',
        submittedCount: 15,
        totalStudents: 41,
        reportUrl: '/practice-reports?plan=plan-001&day=3',
        startTime: '6月14日 09:00',
        deadline: '6月14日 23:59',
        id: 'plan-001-day-3',
      },
      {
        dayIndex: 5,
        dayLabel: 'Day 5 复习收口任务',
        taskType: 'closeout',
        questionSummary: '24 道主复习题 + 6 道动态回滚题',
        mainQuestionCount: 24,
        rollbackQuestionCount: 6,
        status: 'not_started',
        submittedCount: 0,
        totalStudents: 41,
        startTime: '6月16日 09:00',
        deadline: '6月16日 23:59',
        id: 'plan-001-day-5',
      },
    ],
    overview: {
      coveredWordCount: 8,
      cumulativeCompletionRate: 0.72,
      masteryImprovement: {
        before: 62,
        after: 71,
        improvement: 9,
        available: true,
      },
      rollbackAccuracy: {
        rate: 76,
        available: true,
      },
    },
  },
  {
    id: 'plan-002',
    title: '当前单元词汇复习计划',
    planType: 'current_unit',
    className: '2023级A18班',
    wordCount: 44,
    dayCount: 7,
    reviewDays: [1, 3, 5, 7],
    taskCount: 4,
    wordsPerDay: 50,
    status: 'not_started',
    progressSummary: '已完成 0/4 份任务',
    currentTaskLabel: undefined,
    publishedAt: '2026-06-15T08:00:00Z',
    goalLabel: '当前单元词汇复习',
    days: [
      {
        dayIndex: 1,
        dayLabel: 'Day 1 复习任务',
        taskType: 'main',
        questionSummary: '50 道主复习题',
        mainQuestionCount: 50,
        rollbackQuestionCount: 0,
        status: 'not_started',
        submittedCount: 0,
        totalStudents: 41,
        startTime: '6月16日 09:00',
        deadline: '6月16日 23:59',
        id: 'plan-002-day-1',
      },
      {
        dayIndex: 3,
        dayLabel: 'Day 3 巩固回滚任务',
        taskType: 'consolidation',
        questionSummary: '40 道主复习题 + 10 道动态回滚题',
        mainQuestionCount: 40,
        rollbackQuestionCount: 10,
        status: 'not_started',
        submittedCount: 0,
        totalStudents: 41,
        startTime: '6月18日 09:00',
        deadline: '6月18日 23:59',
        id: 'plan-002-day-3',
      },
      {
        dayIndex: 5,
        dayLabel: 'Day 5 巩固回滚任务',
        taskType: 'consolidation',
        questionSummary: '40 道主复习题 + 10 道动态回滚题',
        mainQuestionCount: 40,
        rollbackQuestionCount: 10,
        status: 'not_started',
        submittedCount: 0,
        totalStudents: 41,
        startTime: '6月20日 09:00',
        deadline: '6月20日 23:59',
        id: 'plan-002-day-5',
      },
      {
        dayIndex: 7,
        dayLabel: 'Day 7 复习收口任务',
        taskType: 'closeout',
        questionSummary: '40 道主复习题 + 10 道动态回滚题',
        mainQuestionCount: 40,
        rollbackQuestionCount: 10,
        status: 'not_started',
        submittedCount: 0,
        totalStudents: 41,
        startTime: '6月22日 09:00',
        deadline: '6月22日 23:59',
        id: 'plan-002-day-7',
      },
    ],
    overview: {
      coveredWordCount: 44,
      cumulativeCompletionRate: 0,
      masteryImprovement: {
        before: 65,
        after: 65,
        improvement: 0,
        available: false,
      },
      rollbackAccuracy: {
        rate: 0,
        available: false,
      },
    },
  },
  {
    id: 'plan-003',
    title: '草稿词复习计划',
    planType: 'draft_basket',
    className: '2023级A18班',
    wordCount: 5,
    dayCount: 5,
    reviewDays: [1, 3, 5],
    taskCount: 3,
    wordsPerDay: 30,
    status: 'completed',
    progressSummary: '已完成 3/3 份任务',
    publishedAt: '2026-06-01T10:00:00Z',
    goalLabel: '草稿词复习',
    days: [
      {
        dayIndex: 1,
        dayLabel: 'Day 1 复习任务',
        taskType: 'main',
        questionSummary: '30 道主复习题',
        mainQuestionCount: 30,
        rollbackQuestionCount: 0,
        status: 'completed',
        submittedCount: 41,
        totalStudents: 41,
        reportUrl: '/practice-reports?plan=plan-003&day=1',
        startTime: '6月2日 09:00',
        deadline: '6月2日 23:59',
        id: 'plan-003-day-1',
      },
      {
        dayIndex: 3,
        dayLabel: 'Day 3 巩固回滚任务',
        taskType: 'consolidation',
        questionSummary: '24 道主复习题 + 6 道动态回滚题',
        mainQuestionCount: 24,
        rollbackQuestionCount: 6,
        status: 'completed',
        submittedCount: 39,
        totalStudents: 41,
        reportUrl: '/practice-reports?plan=plan-003&day=3',
        startTime: '6月4日 09:00',
        deadline: '6月4日 23:59',
        id: 'plan-003-day-3',
      },
      {
        dayIndex: 5,
        dayLabel: 'Day 5 复习收口任务',
        taskType: 'closeout',
        questionSummary: '24 道主复习题 + 6 道动态回滚题',
        mainQuestionCount: 24,
        rollbackQuestionCount: 6,
        status: 'completed',
        submittedCount: 38,
        totalStudents: 41,
        reportUrl: '/practice-reports?plan=plan-003&day=5',
        startTime: '6月6日 09:00',
        deadline: '6月6日 23:59',
        id: 'plan-003-day-5',
      },
    ],
    overview: {
      coveredWordCount: 5,
      cumulativeCompletionRate: 1.0,
      masteryImprovement: {
        before: 58,
        after: 81,
        improvement: 23,
        available: true,
      },
      rollbackAccuracy: {
        rate: 82,
        available: true,
      },
    },
  },
]
